version: 0.0
os: linux
files:
   - source: /
     destination: /var/www/html
hooks:
   BeforeInstall:
    - location: installapache.sh
      runas: root
    - location: startapache.sh
      runas: root
   AfterInstall:
    - location: restartapache.sh
      runas: root
