version: 0.0
os: linux
files:
   - source: source
     destination: /var/www/html
hooks:
   BeforeInstall:
    - location: Scripts/installapache.sh
      runas: root
    - location: Scripts/startapache.sh
      runas: root
   AfterInstall:
    - location: Scripts/restartapache.sh
      runas: root
